# Generated by Django 2.2.6 on 2020-12-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20201029_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='short_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre Corto'),
        ),
    ]
